language: node_js
branches:
  except:
    - gh-pages
sudo: false
node_js:
  - "12"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test:coverage
  # - npm run package
  - npm run codecov
notifications:
  email:
    on_success: change
    on_failure: change
